from django.db import models

class Pulsar(models.Model):
    Name = models.CharField(max_length=200, help_text="Pulsar name.  The B name if exists, otherwise the J name.")
    P0 = models.DecimalField(max_digits=32, decimal_places=30, null=True)
    P1 = models.FloatField(null=True)
    F0 = models.DecimalField(max_digits=36, decimal_places=30, null=True)
    F1 = models.FloatField(null=True)
    F2 = models.FloatField(null=True)
    F3 = models.FloatField(null=True)
    DM = models.FloatField(null=True)
    DM1 = models.FloatField(null=True)
    RM = models.FloatField(null=True)
    W50 = models.FloatField(null=True)
    W10 = models.FloatField(null=True)
    S400 = models.FloatField(null=True)
    S1400 = models.FloatField(null=True)
    S2000 = models.FloatField(null=True)
    Dist = models.FloatField(null=True)
    Age = models.FloatField(null=True)
    Bsurf = models.FloatField(null=True)
    Edot = models.FloatField(null=True)
    P0_rr = models.FloatField(null=True)
    P1_rr = models.FloatField(null=True)
    F1_rr = models.FloatField(null=True)
    F2_rr = models.FloatField(null=True)
    F3_rr = models.FloatField(null=True)
    DM_rr = models.FloatField(null=True)
    DM1_rr = models.FloatField(null=True)
    RM_rr = models.FloatField(null=True)
    W50_rr = models.FloatField(null=True)
    W10_rr = models.FloatField(null=True)
    S400_rr = models.FloatField(null=True)
    S1400_rr = models.FloatField(null=True)
    S2000_rr = models.FloatField(null=True)
