# Generated by Django 2.2.6 on 2020-04-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsar',
            name='Name',
            field=models.CharField(max_length=200, verbose_name='Pulsar name.  The B name if exists, otherwise the J name.'),
        ),
    ]
