# Generated by Django 2.2.6 on 2020-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200430_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsar',
            name='Name',
            field=models.CharField(help_text='Pulsar name.  The B name if exists, otherwise the J name.', max_length=200),
        ),
    ]
