# Generated by Django 2.2.6 on 2020-06-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsar',
            name='observations',
            field=models.ManyToManyField(to='database.Observation'),
        ),
    ]
